function make()
    % KDL_IK.make Makes a mex-file of the CPP implementation of the MEX
    % adapter in the C++ directory.
    %
    % This function can be called from matlab to perform inverse kinematics
    % using KDL library
    
    IKdir = utils.QuIK_root;
    opt = config;
    
    % Define library folders and includes
    srcFolder = fullfile(IKdir, 'C++', 'KDL_IK');
    adapterFile = fullfile(srcFolder, 'IK_mexAdapter.cpp');
    mexFile = fullfile(IKdir, 'matlab', '+KDL_IK', 'IK');
    
    assert(~isempty( opt.Eigen3Dir ), 'You must specify a path to an Eigen 3 directory!');
    disp("Compiling KDL c++ library into a mex-file...");
        
    % Mex file
    mex(adapterFile, ...
        fullfile(srcFolder, 'KDL-1.5.0', '*.cpp'), ...
        fullfile(srcFolder, 'KDL-1.5.0', '*.cxx'), ...
        fullfile(srcFolder, 'KDL-1.5.0', 'utilities', '*.cpp'), ...
        fullfile(srcFolder, 'KDL-1.5.0', 'utilities', '*.cxx'), ...
        '-R2018a', ...
        ['-I', opt.Eigen3Dir], ...
        ['-I', srcFolder], ...
        ['-I', fullfile(srcFolder, 'KDL')], ...
        ['-I', fullfile(srcFolder, 'KDL-1.5.0')], ...
        ['-I', fullfile(srcFolder, 'KDL-1.5.0', 'utilities')], ...
        '-output', mexFile);
    
end